// Generated by https://quicktype.io

export interface AirTableData {
    records: Record[];
}

export interface Record {
    id:          string;
    createdTime: string;
    fields:      Fields;
}

export interface Fields {
    cost:                   number;
    title:                  string;
    components?:            string[];
    dmg_type?:              DmgType[];
    weight:                 number;
    effects:                string[];
    item_type:              ItemType;
    crafting_requierments?: string[];
    tags:                   string[];
    airtable_id:            string;
    image?:                 Image[];
    description?:           string;
}

export enum DmgType {
    Blunt = "Blunt",
    Pierce = "Pierce",
    Slash = "Slash",
}

export interface Image {
    id:         string;
    width:      number;
    height:     number;
    url:        string;
    filename:   string;
    size:       number;
    type:       string;
    thumbnails: Thumbnails;
}

export interface Thumbnails {
    small: Full;
    large: Full;
    full:  Full;
}

export interface Full {
    url:    string;
    width:  number;
    height: number;
}

export enum ItemType {
    Weapon = "Weapon",
}
